Controllers/EmployeeManagerController.cs
using EmployeeManager.ApiClient.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading.Tasks;

namespace EmployeeManager.ApiClient.Controllers
{
    public class EmployeeManagerController : Controller
    {
        private readonly HttpClient client = null;
        private string employeesApiUrl = "";
        private string countriesApiUrl = "";

        //private WebApiConfig config = null;

        public EmployeeManagerController(HttpClient client, IConfiguration config)
        {
            this.client = client;
            employeesApiUrl = config.GetValue<string>("AppSettings:EmployeesApiUrl");
            countriesApiUrl = config.GetValue<string>("AppSettings:CountriesApiUrl");

            //add IOptions<WebApiConfig> parameter to 
            //constructor and uncomment the following code
            //this.config = options.Value;
            //employeesApiUrl = this.config.EmployeesApiUrl;
            //countriesApiUrl = this.config.CountriesApiUrl;
        }

        public async Task<bool> FillCountriesAsync()
        {
            HttpResponseMessage response = await client.GetAsync(countriesApiUrl);
            string stringData = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            List<Country> listCountries = JsonSerializer.Deserialize<List<Country>>
            (stringData, options);
            List<SelectListItem> countries = (from c in listCountries
                                              select new SelectListItem()
                                              { Text = c.Name, Value = c.Name }).ToList();
            ViewBag.Countries = countries;
            return true;
        }

        public async Task<IActionResult> ListAsync()
        {
            HttpResponseMessage response = await client.GetAsync(employeesApiUrl);
            string stringData = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };

            List<Employee> data = JsonSerializer.Deserialize
                <List<Employee>>(stringData, options);
            return View(data);
        }
        public async Task<IActionResult> InsertAsync()
        {
            await FillCountriesAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InsertAsync(Employee model)
        {
            await FillCountriesAsync();
            if (ModelState.IsValid) 
            {
                string stringData = JsonSerializer.Serialize(model);
                var contentData = new StringContent(stringData, System.Text.
                    Encoding.UTF8, "application/json");
                HttpResponseMessage response = await client.PostAsync
                    (employeesApiUrl, contentData);
                if (response.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Employee inserted successfully!";
                }
                else
                {
                    ViewBag.Message = "Error while calling Web API!";
                }
            }
            return View(model);
        }

        public async Task<IActionResult> UpdateAsync(int id)
        {
            await FillCountriesAsync();
            HttpResponseMessage response = await client.GetAsync($"{employeesApiUrl}/{id}");
            string stringData = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            Employee model = JsonSerializer.Deserialize<Employee>(stringData, options);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateAsync(Employee model)
        {
            await FillCountriesAsync();
            if (ModelState.IsValid)
            {
                string stringData = JsonSerializer.Serialize(model);
                var contentData = new StringContent(stringData,
                    System.Text.Encoding.UTF8, "application/json");
                HttpResponseMessage response = await client.PutAsync
                    ($"{employeesApiUrl}/{model.EmployeeID}", contentData);
                if (response.IsSuccessStatusCode)
                {
                    ViewBag.Message = "Employee updated successfully!";
                }
                else 
                {
                    ViewBag.Message = "Error while calling Web API!";
                }
            }
            return View(model);
        }

        [ActionName("Delete")]
        public async Task<IActionResult> ConfirmDeleteAsync(int id)
        {
            HttpResponseMessage response = await client.
                GetAsync($"{employeesApiUrl}/{id}");
            string stringData = await response.Content.ReadAsStringAsync();
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true
            };
            Employee model = JsonSerializer.Deserialize<Employee>(stringData,options);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAsync(int employeeID)
        {
            HttpResponseMessage response = await client.
                DeleteAsync($"{employeesApiUrl}/{employeeID}");
            if (response.IsSuccessStatusCode)
            {
                TempData["Message"] = "Employee deleted successfully!";
            }
            else
            {
                TempData["Message"] = "Error while calling Web API!";
            }
            return RedirectToAction("List");
        }


        //public IActionResult Index()
        //{
        //    return View();
        //}
    }
}

Views/EmployeeManager/Delete.cshtml
@model Employee

<h2>Delete Existing Employee</h2>
<h3 class="message">
    Warning : You are about to delete an employee record.
</h3>

@using (Html.BeginForm("Delete", "EmployeeManager", FormMethod.Post))
{
    @Html.HiddenFor(m => m.EmployeeID)
    

    <table border="0">
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.EmployeeID) :
            </td>
            <td>
                @Model.EmployeeID
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.FirstName) :
            </td>
            <td>
                @Model.FirstName
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.LastName) :
            </td>
            <td>
                @Model.LastName
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.Title) :
            </td>
            <td>
                @Model.Title
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.BirthDate) :
            </td>
            <td>
                @Model.BirthDate.ToString("dd MMMM yyyy")
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.HireDate) :
            </td>
            <td>
                @Model.HireDate.ToString("dd MMMM yyyy")
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.Notes) :
            </td>
            <td>
                @Model.Notes
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Delete</button>
            </td>
        </tr>
    </table>
}

Views/EmployeeManager/Insert.cshtml
@model Employee

<h2>Insert New Employee</h2>
<h3 class="message">@ViewBag.Message</h3>

@using (Html.BeginForm("Insert", "EmployeeManager", FormMethod.Post))
{
    <table border="0">
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.FirstName) :
            </td>
            <td>
                @Html.TextBoxFor(m => m.FirstName)
                @Html.ValidationMessageFor(m => m.FirstName, null, new { @class = "message" })
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.LastName) :
            </td>
            <td>
                @Html.TextBoxFor(m => m.LastName)
                @Html.ValidationMessageFor(m => m.LastName, null, new { @class = "message" })
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.Title) :
            </td>
            <td>
                @Html.TextBoxFor(m => m.Title)
                @Html.ValidationMessageFor(m => m.Title, null, new { @class = "message" })
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.BirthDate) :
            </td>
            <td>
                @Html.TextBoxFor(m => m.BirthDate, null, new { type = "date" })
                @Html.ValidationMessageFor(m => m.BirthDate, null, new { @class = "message" })
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.HireDate) :
            </td>
            <td>
                @Html.TextBoxFor(m => m.HireDate, null, new { type = "date" })
                @Html.ValidationMessageFor(m => m.HireDate, null, new { @class = "message" })
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.Country) :
            </td>
            <td>
                @Html.DropDownListFor(m => m.Country, ViewBag.Countries as List<SelectListItem>, "Please select")
                @Html.ValidationMessageFor(m => m.Country, null, new { @class = "message" })
            </td>
        </tr>
        <tr>
            <td class="right">
                @Html.LabelFor(m => m.Notes) :
            </td>
            <td>
                @Html.TextAreaFor(m => m.Notes, 5, 40, null)
                @Html.ValidationMessageFor(m => m.Notes, null, new { @class = "message" })
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Save</button>
            </td>
        </tr>
    </table>
}

<br />
<br />

@Html.ActionLink("Back to Employee Listing", "List", "EmployeeManager")

Views/EmployeeManager/List.cshtml
@model List<Employee>

<h2>List of Employees</h2>

<h3 class="message">@TempData["Message"]</h3>

@Html.ActionLink("Insert", "Insert", "EmployeeManager", null, new
{
    @class = "linkbutton"
})
<br />
<br />

<table border="1">
    <tr>
        <th>Employee ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Title</th>
        <th colspan="2">Actions</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.EmployeeID</td>
            <td>@item.FirstName</td>
            <td>@item.LastName</td>
            <td>@item.Title</td>
            <td>
                @Html.ActionLink("Update", "Update", "EmployeeManager", new
                { id = item.EmployeeID }, new { @class = "linkbutton" })
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", "EmployeeManager", new
                { id = item.EmployeeID }, new { @class = "linkbutton" })
            </td>
        </tr>
    }
</table>

Views/EmployeeManager/Update.cshtml
@model Employee

<h2>Update Existing Employee</h2>
<h3 class="message">@ViewBag.Message</h3>

@using (Html.BeginForm("Update", "EmployeeManager", FormMethod.Post))
{
<table border="0">
    <tr>
        <td class="right">
            @Html.LabelFor(m => m.EmployeeID) :
        </td>
        <td>
            @Html.HiddenFor(m => m.EmployeeID)
            <span>@Model.EmployeeID</span>
        </td>
    </tr>
    <tr>
        <td class="right">
            @Html.LabelFor(m => m.FirstName) :
        </td>
        <td>
            @Html.TextBoxFor(m => m.FirstName)
            @Html.ValidationMessageFor(m => m.FirstName, null, new { @class = "message" })
        </td>
    </tr>
    <tr>
        <td class="right">
            @Html.LabelFor(m => m.LastName) :
        </td>
        <td>
            @Html.TextBoxFor(m => m.LastName)
            @Html.ValidationMessageFor(m => m.LastName, null, new { @class = "message" })
        </td>
    </tr>
    <tr>
        <td class="right">
            @Html.LabelFor(m => m.Title) :
        </td>
        <td>
            @Html.TextBoxFor(m => m.Title)
            @Html.ValidationMessageFor(m => m.Title, null, new { @class = "message" })
        </td>
    </tr>
    <tr>
        <td class="right">
            @Html.LabelFor(m => m.BirthDate) :
        </td>
        <td>
            @Html.TextBoxFor(m => m.BirthDate, "{0:yyyy-MM-dd}", new { type = "date" })
            @Html.ValidationMessageFor(m => m.BirthDate, null, new { @class = "message" })
        </td>
    </tr>
    <tr>
        <td class="right">
            @Html.LabelFor(m => m.HireDate) :
        </td>
        <td>
            @Html.TextBoxFor(m => m.HireDate, "{0:yyyy-MM-dd}", new { type = "date" })
            @Html.ValidationMessageFor(m => m.HireDate, null, new { @class = "message" })
        </td>
    </tr>
    <tr>
        <td class="right">
            @Html.LabelFor(m => m.Country) :
        </td>
        <td>
            @Html.DropDownListFor(m => m.Country, ViewBag.Countries as List<SelectListItem>)
            @Html.ValidationMessageFor(m => m.Country, null, new { @class = "message" })
        </td>
    </tr>
    <tr>
        <td class="right">
            @Html.LabelFor(m => m.Notes) :
        </td>
        <td>
            @Html.TextAreaFor(m => m.Notes, 5, 40, null)
            @Html.ValidationMessageFor(m => m.Notes, null, new { @class = "message" })
        </td>
    </tr>
    <tr>
        <td colspan="2">
            <button type="submit">Save</button>
        </td>
    </tr>
</table>
}